export const types = {
    GET_CONTINENTS_DATA_LOADING: "GET_CONTINENTS_DATA_LOADING",
    GET_CONTINENTS_DATA_REQUEST: "GET_CONTINENTS_DATA_REQUEST",
    GET_COUNTRY_DATA_LOADING: "GET_COUNTRY_DATA_LOADING",
    GET_COUNTRY_DATA_REQUEST: "GET_COUNTRY_DATA_REQUEST",
    GET_VACCINES_DATA_LOADING: "GET_VACCINES_DATA_LOADING",
    GET_VACCINES_DATA_REQUEST: "GET_VACCINES_DATA_REQUEST",
    GET_VACCINES_COUNTRY_DATA_LOADING: "GET_VACCINES_COUNTRY_DATA_LOADING",
    GET_VACCINES_COUNTRY_DATA_REQUEST: "GET_VACCINES_COUNTRY_DATA_REQUEST"
};